version: "2.2"
services:
  iris:
    init: true
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports: 
      - 1972
      - 52773
    volumes:
      - ./:/irisdev/app
